import type { Metadata } from 'next'
import { Shadows_Into_Light } from 'next/font/google'
import './globals.css'

const shadowsIntoLight = Shadows_Into_Light({
  variable: '--font-shadows-into-light',
  subsets: ['latin'],
  weight: '400',
})

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// })

export const metadata: Metadata = {
  title: 'Jio Mosaic',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={` ${shadowsIntoLight.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
